name: Trigger performance testing on Polaris

on:
  workflow_dispatch: {}
#  push:
#    branches:
#    - main

jobs:
  polaris:
    runs-on: ubuntu-22.04
    steps:
    - name: Trigger gitlab-ci
      run: |
        curl -X POST --fail \
             -F token=${{ secrets.ALCF_GITLAB_CI_TOKEN }} \
             -F ref=main \
             -F variables[MOFKA_GITHUB_SHA]=${{ github.sha }} \
             https://gitlab-ci.alcf.anl.gov/api/v4/projects/122/trigger/pipeline
