name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Set install root for Spack
      run: |
        spack -e tests config add config:install_tree:root:/opt/spack
        spack -e tests config add view:/opt/view

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dclv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_PYTHON=ON \
                 -DCMAKE_BUILD_TYPE=RelWithDebInfo
        make
        ctest -VV --output-on-failure

#    - name: Push packages to buildcache and update index
#      if: ${{ !cancelled() }}
#      run: |
#        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
#        spack -e tests mirror set --push \
#          --oci-username ${{ github.actor }} \
#          --oci-password-variable GITHUB_TOKEN mochi-buildcache
#        spack -e tests buildcache push --base-image ubuntu:22.04 \
#          --unsigned --update-index mochi-buildcache
